@startuml BounceBall
class BounceBall
class Game{
    - Player : player[1]
    -Event : events[]
    -Audio : audio[1]
}
class Menu{
    -Font : font[1]
}
class Player
class Event
class Font
class Audio{
    -Music : music[2]
}
class Music

Game "1" *-- "1" Player
Game "1" *-- "*" Event
Game "1" *-- "1" Audio
Menu "1" *-- "1" Font
Audio "1" *-- "2" Music

Player o-- Menu

Game <-- BounceBall 

Game : initGame()
Game : resetGame()
Game : checkCollisions()
Game : createCollectibles()
Game : createObstacles()
Game : initFonts()
Game : initText()
Game : isRunning()
Game : handleEvents()
Game : updateText()
Game : renderText()
Game : update()
Game : render()
Game : resetGoalPosition()
Game : resetGameElements()

Menu : moveUp()
Menu : moveDown()
Menu : getMenuPressed()
Menu : draw()
Menu : initBackgroud()
Menu : initTitle()

Player : initVariables()
Player : initTexture()
Player : initSprite()
Player : initAnimations()
Player : updateAnimatios()
Player : updateInput()
Player : updateWindowBoundCollision()
Player : update()
Player : render()
Player : getBounds()
Player : update()

Music : loadBackgroundMusic()
Music : playBackgroundMusic()
Music : stopBackgroundMusic()

Audio : loadMusic()
Audio : playMusic()
Audio : stopMusic()